version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 3306
    volumes:
      - database:/var/lib/mysql
  php:
    build:
      context: .docker/php
    volumes:
      - .:/demo.test
    ports:
      - 9000
    links:
      - db
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/demo.test:ro
      - .docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  database:
