version: "3"
services:
  php:
    image: php:7.1-fpm-alpine
    volumes:
      - .:/demo.test
    ports:
      - 9000
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/demo.test:ro
      - .docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
